import type { SymbolDef } from '../types';
import { CurrentArrow, LoopArrow, VoltageArrow } from '../shapes/misc';
import { ComplexAxes, VectorArrow } from '../shapes/blocks';
import { def } from './common';

/** Аннотации для расчётных схем. */
export const ANNOTATIONS_SYMBOLS: SymbolDef[] = [
  def({
    type: 'currentArrow',
    title: 'Стрелка тока',
    category: 'annotations',
    keywords: 'I направление ток стрелка',
    ports: [],
    bbox: { x: -24, y: -8, w: 48, h: 16 },
    prefix: 'I',
    defaultValue: '',
    defaultUnit: '',
    showValue: false,
    hasPolarity: true,
    Shape: CurrentArrow,
  }),
  def({
    type: 'voltageArrow',
    title: 'Стрелка напряжения',
    category: 'annotations',
    keywords: 'U напряжение стрелка',
    ports: [],
    bbox: { x: -30, y: -10, w: 60, h: 20 },
    prefix: 'U',
    defaultValue: '',
    defaultUnit: '',
    showValue: false,
    hasPolarity: true,
    Shape: VoltageArrow,
  }),
  def({
    type: 'loopArrow',
    title: 'Обход контура',
    category: 'annotations',
    keywords: 'контур обход направление',
    ports: [],
    bbox: { x: -24, y: -24, w: 48, h: 48 },
    prefix: '',
    defaultValue: '',
    defaultUnit: '',
    showValue: false,
    hasPolarity: true,
    Shape: LoopArrow,
  }),
  def({
    type: 'vector',
    title: 'Вектор диаграммы',
    category: 'annotations',
    keywords: 'вектор диаграмма комплексная амплитуда',
    ports: [],
    bbox: { x: 0, y: -8, w: 62, h: 16 },
    prefix: 'U',
    defaultValue: '',
    defaultUnit: '',
    showValue: false,
    hasPolarity: false,
    Shape: VectorArrow,
  }),
  def({
    type: 'axes',
    title: 'Оси +1 / +j',
    category: 'annotations',
    keywords: 'оси координат комплексная плоскость диаграмма',
    ports: [],
    bbox: { x: -12, y: -104, w: 116, h: 128 },
    prefix: '',
    defaultValue: '',
    defaultUnit: '',
    showValue: false,
    hasPolarity: false,
    Shape: ComplexAxes,
  }),
];
