import type { SymbolDef } from '../types';
import { Capacitor, CapacitorPol, Inductor, MutualInductance, Resistor, ResistorTrim, ResistorVar } from '../shapes/passive';
import { ResistorNonlinear } from '../shapes/blocks';
import { def, twoPort } from './common';

/** Пассивные элементы. */
export const PASSIVE_SYMBOLS: SymbolDef[] = [
  def({
    type: 'resistor',
    title: 'Резистор',
    category: 'passive',
    keywords: 'resistor R сопротивление',
    ports: twoPort,
    bbox: { x: -40, y: -10, w: 80, h: 20 },
    prefix: 'R',
    defaultValue: '100',
    defaultUnit: 'Ом',
    showValue: true,
    hasPolarity: false,
    Shape: Resistor,
  }),
  def({
    type: 'resistorVar',
    title: 'Резистор переменный',
    category: 'passive',
    keywords: 'потенциометр реостат variable',
    ports: twoPort,
    bbox: { x: -40, y: -20, w: 80, h: 40 },
    prefix: 'R',
    defaultValue: '100',
    defaultUnit: 'Ом',
    showValue: true,
    hasPolarity: false,
    Shape: ResistorVar,
  }),
  def({
    type: 'resistorTrim',
    title: 'Резистор подстроечный',
    category: 'passive',
    keywords: 'trimmer подстроечный',
    ports: twoPort,
    bbox: { x: -40, y: -20, w: 80, h: 40 },
    prefix: 'R',
    defaultValue: '100',
    defaultUnit: 'Ом',
    showValue: true,
    hasPolarity: false,
    Shape: ResistorTrim,
  }),
  def({
    type: 'capacitor',
    title: 'Конденсатор',
    category: 'passive',
    keywords: 'capacitor C ёмкость емкость',
    ports: twoPort,
    bbox: { x: -40, y: -16, w: 80, h: 32 },
    prefix: 'C',
    defaultValue: '10',
    defaultUnit: 'мкФ',
    showValue: true,
    hasPolarity: false,
    Shape: Capacitor,
  }),
  def({
    type: 'capacitorPol',
    title: 'Конденсатор полярный',
    category: 'passive',
    keywords: 'электролитический polarized',
    ports: twoPort,
    bbox: { x: -40, y: -16, w: 80, h: 32 },
    prefix: 'C',
    defaultValue: '100',
    defaultUnit: 'мкФ',
    showValue: true,
    hasPolarity: false,
    Shape: CapacitorPol,
  }),
  def({
    type: 'inductor',
    title: 'Катушка индуктивности',
    category: 'passive',
    keywords: 'inductor L индуктивность дроссель',
    ports: twoPort,
    bbox: { x: -40, y: -14, w: 80, h: 28 },
    prefix: 'L',
    defaultValue: '10',
    defaultUnit: 'мГн',
    showValue: true,
    hasPolarity: false,
    Shape: Inductor,
  }),
  def({
    type: 'mutualInductance',
    title: 'Взаимная индуктивность',
    category: 'passive',
    keywords: 'связанные катушки M взаимоиндукция',
    ports: [
      { x: -60, y: -20 },
      { x: 60, y: -20 },
      { x: -60, y: 20 },
      { x: 60, y: 20 },
    ],
    bbox: { x: -60, y: -34, w: 120, h: 68 },
    prefix: 'M',
    defaultValue: '5',
    defaultUnit: 'мГн',
    showValue: true,
    hasPolarity: false,
    Shape: MutualInductance,
  }),
  def({
    type: 'resistorNonlinear',
    title: 'Нелинейный резистор',
    category: 'passive',
    keywords: 'варистор терморезистор нелинейный',
    ports: twoPort,
    bbox: { x: -40, y: -16, w: 80, h: 32 },
    prefix: 'R',
    defaultValue: '',
    defaultUnit: '',
    showValue: false,
    hasPolarity: false,
    Shape: ResistorNonlinear,
  }),
];
