import type { SymbolDef } from '../types';
import { Diode } from '../shapes/misc';
import { Led, Thyristor, TransistorFet, TransistorNpn, TransistorPnp, Zener } from '../shapes/semiconductors';
import { def, twoPort } from './common';

const bipolarPorts = [
  { x: -40, y: 0 },
  { x: 20, y: -40 },
  { x: 20, y: 40 },
];
const bipolarBox = { x: -40, y: -44, w: 80, h: 88 };

/** Полупроводниковые приборы для раздела компьютерной электроники. */
export const SEMICONDUCTORS_SYMBOLS: SymbolDef[] = [
  def({
    type: 'diode',
    title: 'Диод',
    category: 'semiconductors',
    keywords: 'diode вентиль VD выпрямитель',
    ports: twoPort,
    bbox: { x: -40, y: -13, w: 80, h: 26 },
    prefix: 'VD',
    defaultValue: '',
    defaultUnit: '',
    showValue: false,
    hasPolarity: true,
    Shape: Diode,
  }),
  def({
    type: 'zener',
    title: 'Стабилитрон',
    category: 'semiconductors',
    keywords: 'zener опорное напряжение VD',
    ports: twoPort,
    bbox: { x: -40, y: -17, w: 80, h: 34 },
    prefix: 'VD',
    defaultValue: '',
    defaultUnit: '',
    showValue: false,
    hasPolarity: true,
    Shape: Zener,
  }),
  def({
    type: 'led',
    title: 'Светодиод',
    category: 'semiconductors',
    keywords: 'led светоизлучающий HL',
    ports: twoPort,
    bbox: { x: -40, y: -30, w: 80, h: 43 },
    prefix: 'HL',
    defaultValue: '',
    defaultUnit: '',
    showValue: false,
    hasPolarity: true,
    Shape: Led,
  }),
  def({
    type: 'thyristor',
    title: 'Тиристор',
    category: 'semiconductors',
    keywords: 'тиристор управляемый вентиль VS',
    ports: [
      { x: -40, y: 0 },
      { x: 40, y: 0 },
      { x: 20, y: 40 },
    ],
    bbox: { x: -40, y: -13, w: 80, h: 53 },
    prefix: 'VS',
    defaultValue: '',
    defaultUnit: '',
    showValue: false,
    hasPolarity: true,
    Shape: Thyristor,
  }),
  def({
    type: 'transistorNpn',
    title: 'Транзистор n-p-n',
    category: 'semiconductors',
    keywords: 'биполярный npn VT транзистор',
    ports: bipolarPorts,
    bbox: bipolarBox,
    prefix: 'VT',
    defaultValue: '',
    defaultUnit: '',
    showValue: false,
    hasPolarity: false,
    Shape: TransistorNpn,
  }),
  def({
    type: 'transistorPnp',
    title: 'Транзистор p-n-p',
    category: 'semiconductors',
    keywords: 'биполярный pnp VT транзистор',
    ports: bipolarPorts,
    bbox: bipolarBox,
    prefix: 'VT',
    defaultValue: '',
    defaultUnit: '',
    showValue: false,
    hasPolarity: false,
    Shape: TransistorPnp,
  }),
  def({
    type: 'transistorFet',
    title: 'Полевой транзистор',
    category: 'semiconductors',
    keywords: 'мдп моп mosfet затвор VT',
    ports: bipolarPorts,
    bbox: bipolarBox,
    prefix: 'VT',
    defaultValue: '',
    defaultUnit: '',
    showValue: false,
    hasPolarity: false,
    Shape: TransistorFet,
  }),
];
