import type { SymbolDef } from '../types';
import { Battery, SourceAc, SourceCurrent, SourceEmf, SourceVoltage } from '../shapes/sources';
import { def, twoPort, wideBox } from './common';

/** Источники ЭДС, тока и напряжения. */
export const SOURCES_SYMBOLS: SymbolDef[] = [
  def({
    type: 'sourceEmf',
    title: 'Источник ЭДС',
    category: 'sources',
    keywords: 'E ЭДС emf источник',
    ports: twoPort,
    bbox: wideBox,
    prefix: 'E',
    defaultValue: '12',
    defaultUnit: 'В',
    showValue: true,
    hasPolarity: true,
    Shape: SourceEmf,
  }),
  def({
    type: 'sourceCurrent',
    title: 'Источник тока',
    category: 'sources',
    keywords: 'J ток источник current',
    ports: twoPort,
    bbox: wideBox,
    prefix: 'J',
    defaultValue: '1',
    defaultUnit: 'А',
    showValue: true,
    hasPolarity: true,
    Shape: SourceCurrent,
  }),
  def({
    type: 'sourceVoltage',
    title: 'Источник напряжения',
    category: 'sources',
    keywords: 'U напряжение идеальный voltage',
    ports: twoPort,
    bbox: wideBox,
    prefix: 'U',
    defaultValue: '10',
    defaultUnit: 'В',
    showValue: true,
    hasPolarity: true,
    Shape: SourceVoltage,
  }),
  def({
    type: 'battery',
    title: 'Гальванический элемент',
    category: 'sources',
    keywords: 'батарея battery аккумулятор',
    ports: twoPort,
    bbox: { x: -40, y: -16, w: 80, h: 32 },
    prefix: 'GB',
    defaultValue: '1.5',
    defaultUnit: 'В',
    showValue: true,
    hasPolarity: true,
    Shape: Battery,
  }),
  def({
    type: 'sourceAc',
    title: 'Источник синусоидальный',
    category: 'sources',
    keywords: 'переменный ток синус ac',
    ports: twoPort,
    bbox: wideBox,
    prefix: 'e',
    defaultValue: '100',
    defaultUnit: 'В',
    showValue: true,
    hasPolarity: false,
    Shape: SourceAc,
  }),
];
