import type { SymbolDef } from '../types';
import { SwitchClosed, SwitchOpen } from '../shapes/switching';
import { Diode, Ground, Junction, Opamp, Terminal, Transformer } from '../shapes/misc';
import { def, twoPort } from './common';

/** Коммутация, полупроводники и служебные обозначения. */
export const SWITCHING_SYMBOLS: SymbolDef[] = [
  def({
    type: 'switchOpen',
    title: 'Ключ разомкнутый',
    category: 'switching',
    keywords: 'выключатель switch рубильник',
    ports: twoPort,
    bbox: { x: -40, y: -20, w: 80, h: 28 },
    prefix: 'S',
    defaultValue: '',
    defaultUnit: '',
    showValue: false,
    hasPolarity: false,
    Shape: SwitchOpen,
  }),
  def({
    type: 'switchClosed',
    title: 'Ключ замкнутый',
    category: 'switching',
    keywords: 'выключатель switch замкнут',
    ports: twoPort,
    bbox: { x: -40, y: -12, w: 80, h: 24 },
    prefix: 'S',
    defaultValue: '',
    defaultUnit: '',
    showValue: false,
    hasPolarity: false,
    Shape: SwitchClosed,
  }),
  def({
    type: 'diode',
    title: 'Диод',
    category: 'switching',
    keywords: 'diode вентиль VD',
    ports: twoPort,
    bbox: { x: -40, y: -13, w: 80, h: 26 },
    prefix: 'VD',
    defaultValue: '',
    defaultUnit: '',
    showValue: false,
    hasPolarity: true,
    Shape: Diode,
  }),
  def({
    type: 'ground',
    title: 'Земля',
    category: 'switching',
    keywords: 'ground общая точка корпус',
    ports: [{ x: 0, y: 0 }],
    bbox: { x: -14, y: -2, w: 28, h: 26 },
    prefix: '',
    defaultValue: '',
    defaultUnit: '',
    showValue: false,
    hasPolarity: false,
    Shape: Ground,
  }),
  def({
    type: 'junction',
    title: 'Узел',
    category: 'switching',
    keywords: 'точка соединение node',
    ports: [{ x: 0, y: 0 }],
    bbox: { x: -6, y: -6, w: 12, h: 12 },
    prefix: '',
    defaultValue: '',
    defaultUnit: '',
    showValue: false,
    hasPolarity: false,
    Shape: Junction,
  }),
  def({
    type: 'terminal',
    title: 'Клемма (зажим)',
    category: 'switching',
    keywords: 'вывод двухполюсник 1 1′ зажим',
    ports: [{ x: 0, y: 0 }],
    bbox: { x: -7, y: -7, w: 14, h: 14 },
    prefix: '',
    defaultValue: '',
    defaultUnit: '',
    showValue: false,
    hasPolarity: false,
    Shape: Terminal,
  }),
  def({
    type: 'opamp',
    title: 'Операционный усилитель',
    category: 'switching',
    keywords: 'ОУ opamp усилитель DA',
    ports: [
      { x: -40, y: -20 },
      { x: -40, y: 20 },
      { x: 40, y: 0 },
    ],
    bbox: { x: -40, y: -34, w: 80, h: 68 },
    prefix: 'DA',
    defaultValue: '',
    defaultUnit: '',
    showValue: false,
    hasPolarity: false,
    Shape: Opamp,
  }),
  def({
    type: 'transformer',
    title: 'Трансформатор',
    category: 'switching',
    keywords: 'transformer обмотки TV',
    ports: [
      { x: -40, y: -40 },
      { x: -40, y: 40 },
      { x: 40, y: -40 },
      { x: 40, y: 40 },
    ],
    bbox: { x: -40, y: -44, w: 80, h: 88 },
    prefix: 'TV',
    defaultValue: '',
    defaultUnit: '',
    showValue: false,
    hasPolarity: false,
    Shape: Transformer,
  }),
];
