import type { SymbolDef } from '../types';
import { SwitchClosed, SwitchOpen } from '../shapes/switching';
import { Ground, Junction, Terminal } from '../shapes/misc';
import { Fuse } from '../shapes/blocks';
import { def, twoPort } from './common';

/** Коммутация и служебные обозначения. */
export const SWITCHING_SYMBOLS: SymbolDef[] = [
  def({
    type: 'switchOpen',
    title: 'Ключ разомкнутый',
    category: 'switching',
    keywords: 'выключатель switch рубильник',
    ports: twoPort,
    bbox: { x: -40, y: -20, w: 80, h: 28 },
    prefix: 'S',
    defaultValue: '',
    defaultUnit: '',
    showValue: false,
    hasPolarity: false,
    Shape: SwitchOpen,
  }),
  def({
    type: 'switchClosed',
    title: 'Ключ замкнутый',
    category: 'switching',
    keywords: 'выключатель switch замкнут',
    ports: twoPort,
    bbox: { x: -40, y: -12, w: 80, h: 24 },
    prefix: 'S',
    defaultValue: '',
    defaultUnit: '',
    showValue: false,
    hasPolarity: false,
    Shape: SwitchClosed,
  }),
  def({
    type: 'fuse',
    title: 'Предохранитель',
    category: 'switching',
    keywords: 'плавкая вставка fuse FU',
    ports: twoPort,
    bbox: { x: -40, y: -10, w: 80, h: 20 },
    prefix: 'FU',
    defaultValue: '',
    defaultUnit: '',
    showValue: false,
    hasPolarity: false,
    Shape: Fuse,
  }),
  def({
    type: 'ground',
    title: 'Земля',
    category: 'switching',
    keywords: 'ground общая точка корпус',
    ports: [{ x: 0, y: 0 }],
    bbox: { x: -14, y: -2, w: 28, h: 26 },
    prefix: '',
    defaultValue: '',
    defaultUnit: '',
    showValue: false,
    hasPolarity: false,
    Shape: Ground,
  }),
  def({
    type: 'junction',
    title: 'Узел',
    category: 'switching',
    keywords: 'точка соединение node',
    ports: [{ x: 0, y: 0 }],
    bbox: { x: -6, y: -6, w: 12, h: 12 },
    prefix: '',
    defaultValue: '',
    defaultUnit: '',
    showValue: false,
    hasPolarity: false,
    Shape: Junction,
  }),
  def({
    type: 'terminal',
    title: 'Клемма (зажим)',
    category: 'switching',
    keywords: 'вывод двухполюсник 1 1′ зажим',
    ports: [{ x: 0, y: 0 }],
    bbox: { x: -7, y: -7, w: 14, h: 14 },
    prefix: '',
    defaultValue: '',
    defaultUnit: '',
    showValue: false,
    hasPolarity: false,
    Shape: Terminal,
  }),
];
